### ISSUE TITLE
deployment: Add deployment for the playground app to GithubPages

### ISSUE THREAD

**Issue by ulises-jeremias** [nanlabs/nancy.js#11]
We need to create a new github actions workflow to deploy the playground app to github pages on every push to the main branch

**Comment by ulises-jeremias** [comment]
Example [here](https://github.com/nanlabs/react-webpack-boilerplate/blob/main/.github/workflows/deployment.yml)

**Comment by matiaspompilio** [comment]
Can I take this? @ulises-jeremias

**Comment by ulises-jeremias** [comment]
sure!
