### ISSUE TITLE
state-management: Add libraries to create-react-webpack-project

### ISSUE THREAD

**Issue by ulises-jeremias** [nanlabs/nancy.js#2]
Chat with @ulises-jeremias and/or @rpmolina to coordinate the efforts to add the examples to the [`react-extensions`](https://github.com/Create-Node-App/react-extensions) repo. After that they will be accessible from https://www.npmjs.com/package/create-react-webpack-project

**Comment by Mogakamo** [comment]
@ulises-jeremias I would like to also work on this

**Comment by ulises-jeremias** [comment]
Sure! I'll create specific tickets for this with .ore information today! @Mogakamo

**Comment by Mogakamo** [comment]
Thank you @ulises-jeremias
