### ISSUE TITLE
setup: Add VSCode devcontainer setup

### ISSUE THREAD

**Issue by ulises-jeremias** [nanlabs/nancy.js#5]
We already have a setup example of DevContainer for Node [here](https://github.com/nanlabs/infra-reference/tree/main/examples/devcontainers/nodejs).
We are using it on our boilerplate repo [too](https://github.com/nanlabs/react-webpack-boilerplate).

We want to add it to this repository also to be able to use VSCode devcontainers or codespaces as well

**Comment by corners2wall** [comment]
@ulises-jeremias, sounds easy, assign to me

**Comment by ulises-jeremias** [comment]
Sure!

**Comment by ulises-jeremias** [comment]
@corners2wall hey! do you have any status on this? otherwise, @di3go-martinez can take a look

**Comment by corners2wall** [comment]
@ulises-jeremias, yeap I try, It's more little bit difficult than I thought. And I forgot about this issue
