### ISSUE TITLE
Add useHover hook to @nanlabs/react-hooks

### ISSUE THREAD

**Issue by ulises-jeremias** [nanlabs/nancy.js#94]
### Describe the feature

I would like to request the addition of the `useHover` hook to the `@nanlabs/react-hooks` library. This hook would be designed to track hover state and return the hovered state along with the provided React element.

### Use Case

I frequently need to implement hover effects in my components, and having a dedicated hook for tracking hover state would enhance code organization and reusability.

### Proposed Solution

```ts
import type { MutableRefObject } from 'react';

type TargetValue<T> = T | undefined | null;

type TargetType = HTMLElement | Element | Window | Document;

export type BasicTarget<T extends TargetType = Element> =
  | (() => TargetValue<T>)
  | TargetValue<T>
  | MutableRefObject<TargetValue<T>>;

export interface Options {
  onEnter?: () => void;
  onLeave?: () => void;
  onChange?: (isHovering: boolean) => void;
}

const useHover = (target: BasicTarget, options?: Options): boolean;
```

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### Version used

0.5.3

### Environment details (OS name and version, etc.)

any

**Comment by boredcity** [comment]
I'd be happy to help with this one if you're ok to assign me :)

**Comment by ulises-jeremias** [comment]
@boredcity sure! feel free to start working on it!

You can use the app `apps/playground` to run our storybook to test your implementation before submitting the PR 😊
